export const ALL_PRODUCTS = [
    {
        id: "1",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/bags/shop_2_(2)_1920x1920.webp",
        hoverImage: "/bags/shop_1_(2)_1920x1920.webp",
        gallery: [
            "/bags/shop_2_(2)_1920x1920.webp",
            "/bags/shop_1_(2)_1920x1920.webp",
            "/bags/shop_3_(2)_1920x1920.webp",
        ],
        isNew: true,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "2",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/ball/wallball_8_1920x1920.webp",
        hoverImage: "/ball/wallball_9_1920x1920.webp",
        gallery: [
            "/ball/wallball_8_1920x1920.webp",
            "/ball/wallball_9_1920x1920.webp",
            "/ball/wallball_12_1920x1920.webp",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "3",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/bars/shop_2_(11)_1920x1920.webp",
        hoverImage: "/bars/shop_3_(11)_1920x1920.webp",
        gallery: [
            "/bars/shop_2_(11)_1920x1920.webp",
            "/bars/shop_3_(11)_1920x1920.webp",
            "/bars/shop_4_(11)_1920x1920.webp",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "4",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/centr/rig_target_produkt_02_1920x1920.webp",
        hoverImage: "/centr/rig_target_produkt_03_1920x1920.webp",
        gallery: [
            "/centr/rig_target_produkt_02_1920x1920.webp",
            "/centr/rig_target_produkt_03_1920x1920.webp",
            "/iteams/gym15.jpg",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "5",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/kg/shop_5_(7)_1920x1920.webp",
        hoverImage: "/kg/shop_6_(3)_1920x1920.webp",
        gallery: [
            "/kg/shop_5_(7)_1920x1920.webp",
            "/kg/shop_6_(3)_1920x1920.webp",
            "/color-coded-olympic-competition-bumper-plates-stac.jpg",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "6",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/kg/Centrxhyroxstarterkit.webp",
        hoverImage: "/kg/shop_3_(8)_1920x1920.webp",
        gallery: [
            "/kg/Centrxhyroxstarterkit.webp",
            "/kg/shop_3_(8)_1920x1920.webp",
            "/kg/shop_5_(7)_1920x1920.webp",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "7",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/iteams/gym8.jpg",
        hoverImage: "/iteams/gym9.jpg",
        gallery: [
            "/iteams/gym8.jpg",
            "/iteams/gym9.jpg",
            "/iteams/gym14.jpg",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "8",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/iteams/gym11.jpg",
        hoverImage: "/iteams/gym12.jpg",
        gallery: [
            "/iteams/gym11.jpg",
            "/iteams/gym12.jpg",
            "/iteams/gym16.jpg",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "9",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/bags/shop_3_(2)_1920x1920.webp",
        hoverImage: "/bags/shop_4_(2)_1920x1920.webp",
        gallery: [
            "/bags/shop_3_(2)_1920x1920.webp",
            "/bags/shop_4_(2)_1920x1920.webp",
            "/bags/shop_1_(2)_1920x1920.webp",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "10",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/bars/shop_4_(11)_1920x1920.webp",
        hoverImage: "/bars/shop_5_(8)_1920x1920.webp",
        gallery: [
            "/bars/shop_4_(11)_1920x1920.webp",
            "/bars/shop_5_(8)_1920x1920.webp",
            "/bars/shop_2_(11)_1920x1920.webp",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "11",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/iteams/gym13.jpg",
        hoverImage: "/iteams/gym14.jpg",
        gallery: [
            "/iteams/gym13.jpg",
            "/iteams/gym14.jpg",
            "/iteams/gym11.jpg",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "12",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/iteams/gym15.jpg",
        hoverImage: "/iteams/gym16.jpg",
        gallery: [
            "/iteams/gym15.jpg",
            "/iteams/gym16.jpg",
            "/iteams/gym18.jpg",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "13",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/iteams/gym17.jpg",
        hoverImage: "/iteams/gym18.jpg",
        gallery: [
            "/iteams/gym17.jpg",
            "/iteams/gym18.jpg",
            "/iteams/gym15.jpg",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "14",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/rob/shop_1_(1)_1920x1920.jpg",
        hoverImage: "/rob/shop_2_(1)_1920x1920.jpg",
        gallery: [
            "/rob/shop_1_(1)_1920x1920.jpg",
            "/rob/shop_2_(1)_1920x1920.jpg",
            "/centr/rig_target_produkt_02.webp",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
    {
        id: "15",
        name: "LOREM IPSUM",
        price: "$000.00",
        category: "LOREM IPSUM",
        image: "/push/CENTR x HYROX Competition Power Sled_shop_1_1920x1920.jpg",
        hoverImage: "/push/CENTR x HYROX Competition Power Sled_shop_2_1920x1920.jpg",
        gallery: [
            "/push/CENTR x HYROX Competition Power Sled_shop_1_1920x1920.jpg",
            "/push/CENTR x HYROX Competition Power Sled_shop_2_1920x1920.jpg",
            "/bags/shop_1_(2)_1920x1920.webp",
        ],
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        specs: [
            { label: "LOREM", value: "LOREM" },
            { label: "LOREM", value: "LOREM" },
        ],
    },
]
